export const mockPosts = [
    {
      id: 1,
      title: "Organize your digital assets with a new methodology.",
      excerpt: "In today's digital age, managing and organizing an ever-expanding array of digital assets can be a daunting task.",
      category: "Productivity",
      date: "25 Apr 2023",
      image: "/medicine bottle.png",
    },
    {
      id: 2,
      title: "The Future of Remote Work: Trends to Watch.",
      excerpt: "As remote work becomes the norm, understanding the trends that shape this new landscape is essential for businesses and employees alike.",
      category: "Workplace",
      date: "10 May 2023",
      image: "/capsule.png",
    },
    {
      id: 3,
      title: "10 Tips for Effective Time Management.",
      excerpt: "Mastering time management is crucial for success. Here are ten tips to help you manage your time effectively.",
      category: "Self-Improvement",
      date: "15 Jun 2023",
      image: "/tooth.png",
    },
    {
      id: 4,
      title: "Exploring the Benefits of Mindfulness Meditation.",
      excerpt: "Mindfulness meditation can enhance your mental well-being. Discover the benefits and how to get started.",
      category: "Health & Wellness",
      date: "22 Jul 2023",
      image: "/pils pack.png",
    },
    {
      id: 5,
      title: "A Beginner's Guide to Investing in Cryptocurrency.",
      excerpt: "Cryptocurrency is a rapidly evolving field. Learn the basics of investing in this digital currency.",
      category: "Finance",
      date: "30 Aug 2023",
      image: "thermometer.png",
    },
    {
      id: 6,
      title: "Sustainable Living: Simple Changes for a Greener Future.",
      excerpt: "Making sustainable choices in your daily life can have a big impact. Here are some simple changes to consider.",
      category: "Environment",
      date: "12 Sep 2023",
      image: "microscope.png",
    },
    {
      id: 7,
      title: "The Importance of Networking in Your Career.",
      excerpt: "Building a strong professional network is key to career advancement. Explore effective networking strategies.",
      category: "Career Development",
      date: "18 Oct 2023",
      image: "stethoscope.png",
    },
    {
      id: 8,
      title: "How to Create a Personal Brand Online.",
      excerpt: "In the digital age, personal branding is essential. Learn how to effectively build your online presence.",
      category: "Marketing",
      date: "5 Nov 2023",
      image: "/pils pack.png",
    },
  ];