// Mock data for healthcare facilities
export const facilities = [
    {
      id: 1,
      name: 'Healthcare facility name',
      rating: 4.9,
      reviews: 2500,
      location: 'Ikeja, Lagos',
      services: ['Service 1', 'Service 2', 'Service 3'],
      image: '/oops.png',
      isTopRated: true,
    },
    ,
  {
    id: 2,
    name: 'City Medical Center',
    rating: 4.7,
    reviews: 1800,
    location: 'Victoria Island, Lagos',
    services: ['General Practice', 'Radiology', 'Pharmacy'],
    image: '/oops.png',
    isTopRated: true,
  },
  {
    id: 3,
    name: 'Abuja Specialist Clinic',
    rating: 4.8,
    reviews: 1500,
    location: 'Abuja, Nigeria',
    services: ['Cardiology', 'Dermatology', 'Orthopedics'],
    image: 'oops.png',
    isTopRated: true,
  },
  {
    id: 4,
    name: 'Port Harcourt Health Center',
    rating: 4.5,
    reviews: 1200,
    location: 'Port Harcourt, Nigeria',
    services: ['Family Medicine', 'Nutrition', 'Physical Therapy'],
    image: 'oops.png',
    isTopRated: false,
  },
  {
    id: 5,
    name: 'Enugu Community Hospital',
    rating: 4.6,
    reviews: 900,
    location: 'Enugu, Nigeria',
    services: ['Obstetrics', 'Gynecology', 'Pediatrics'],
    image: 'oops.png',
    isTopRated: false,
  },
  {
    id: 6,
    name: 'Kano Medical Institute',
    rating: 4.4,
    reviews: 800,
    location: 'Kano, Nigeria',
    services: ['General Surgery', 'Anesthesiology', 'Emergency Care'],
    image: 'oops.png',
    isTopRated: false,
  },
  {
    id: 7,
    name: 'Ibadan Health Services',
    rating: 4.3,
    reviews: 700,
    location: 'Ibadan, Nigeria',
    services: ['Internal Medicine', 'Dermatology', 'Psychiatry'],
    image: '/oops.png',
    isTopRated: false,
  },
  {
    id: 8,
    name: 'Lagos Pediatric Clinic',
    rating: 4.9,
    reviews: 3000,
    location: 'Ikeja, Lagos',
    services: ['Pediatrics', 'Vaccination', 'Child Nutrition'],
    image: '/oops.png',
    isTopRated: true,
  },
  {
    id: 9,
    name: 'Abuja Dental Care',
    rating: 4.8,
    reviews: 1100,
    location: 'Abuja, Nigeria',
    services: ['General Dentistry', 'Orthodontics', 'Cosmetic Dentistry'],
    image: '/oops.png',
    isTopRated: true,
  },
  {
    id: 10,
    name: 'Lagos Eye Hospital',
    rating: 4.7,
    reviews: 950,
    location: 'Victoria Island, Lagos',
    services: ['Ophthalmology', 'Optometry', 'Eye Surgery'],
    image: '/oops.png',
    isTopRated: true,
  },
  {
    id: 11,
    name: 'Kano Rehabilitation Center',
    rating: 3.2,
    reviews: 600,
    location: 'Kano, Nigeria',
    services: ['Physical Therapy', 'Occupational Therapy', 'Speech Therapy'],
    image: '/oops.png',
    isTopRated: false,
  },
  {
    id: 12,
    name: 'Port Harcourt Maternity Home',
    rating: 4.5,
    reviews: 500,
    location: 'Port Harcourt, Nigeria',
    services: ['Maternity Care', 'Prenatal Services', 'Postnatal Care'],
    image: '/ploops.png',
    isTopRated: false,
  },
    // ... more facilities
  ]